### ISSUE TITLE
Query support needs to be added

### ISSUE THREAD

**Issue by perezd** [perezd/riemann-nodejs-client#1]
see this page for more information on how queries work:
http://aphyr.github.com/riemann/concepts.html

**Comment by daluu** [comment]
Hey, the referenced link returns 404. What's the current updated link for that?

Also, would be nice if you provided an example in the readme on how to perform an query. You only offer an example to send event.

**Comment by perezd** [comment]
Looks like this is what you want: http://riemann.io/concepts.html

Don't mean to be rude but, you could just read the code or tests :)

**Comment by daluu** [comment]
Thanks, and good point there. But taking that point further, why list out example in readme for sending event if one could just read the code and tests too?

Perhaps I'll just have to fork and make a pull request to update the readme when I figure things out.

**Comment by perezd** [comment]
sure, most people are interested in dispatching events from this context,
rather than querying so I left it out at the time, but you make a good
point. I'd love a pull request!
