### ISSUE TITLE
Can't install using node 0.12.0

### ISSUE THREAD

**Issue by grudzinski** [perezd/riemann-nodejs-client#12]
Currently used protobuf@0.8.6 isn't compatible with node 0.12.0.

**Comment by perezd** [comment]
Does upgrading the dependency fix it? Feel free to submit a PR.

**Comment by Priyanky** [comment]
Is there a fix yet. My exact problem is, the application runs on node12. But we the rpm node package does not work with node12.  So is there any workaround to make it work with node12.

**Comment by perezd** [comment]
I'm unable to repro this, please try upgrading the protobuf dependency and
install it. If that works, please submit a pull request. Thanks!

**Comment by perezd** [comment]
So I think this should be fixed as of that PR. I'll do a release this weekend.
