### ISSUE TITLE
Metric not sent with events

### ISSUE THREAD

**Issue by daluu** [perezd/riemann-nodejs-client#19]
Just tried out this client for our internal monitoring, followed the install steps, and the sample code to get started.

Noticed that the events emitted only contain service name and state (of "ok"), but no metric is passed along even though it is defined. Happens on Ubuntu Linux on an AWS server, and on my local Mac.

I observe a Wireshark trace looks like this of the UDP data sent out from event emitting host:

mbp.local2D......*..ok.&service.name.here".daluu-mbp.local2D......*..ok.&service.name.here".daluu

whereas here's a snippet of my code block:

var monitor = require('riemann').createClient({
  host: 'myhost',
  port: 5555
});
...
monitor.send(monitor.Event({
					  service: 'service.name.here',
						metric: 10.51,
						state: 'ok',
						time: timeCurr
					}));

What could be the problem? Anyone else have such issues?

As a result of this, our riemann server is getting nil for metric.

**Comment by perezd** [comment]
metric gets converted to metricF in nodejs, due to number representation
problems between platforms. Do you see that?

**Comment by daluu** [comment]
Oh, I wasn't aware of that. What is metricF? Is there a workaround or solution to get it to work? I was just following the example code here.

**Comment by perezd** [comment]
It should be working, take a look at the client API requirements:
http://riemann.io/howto.html#write-a-client

A lot of people are successfully using this client in production, I'm not
sure what is unique about your situation. Perhaps ask on the riemann-users
mailing list?

**Comment by daluu** [comment]
Don't know if it was a glitch in the system or not, but for whatever reason, it seemed switching to this forked client worked for me: https://github.com/sandfox/riemann-nodejs-client.

**Comment by perezd** [comment]
Wondering what's different. Can you debug a bit?? What about a pre 1.0
version? We recently changed proto libraries... Would like to rule that out.

**Comment by tanji** [comment]
Hello, same issue here.
Reverting to 0.4.3 fixed the problem.

**Comment by perezd** [comment]
@lovell, can you please investigate this? This appears to be related to the
protobuf change.

**Comment by lovell** [comment]
From memory the system I'm working on uses the Riemann-specified `metric_f` attribute as its values are 32-bit floats.

Perhaps the `metric` attribute should (also? instead?) be copied to `metric_f` approximately [here](https://github.com/perezd/riemann-nodejs-client/blob/master/riemann/client.js#L49).

I'll take a closer look tomorrow.

**Comment by lovell** [comment]
#20 should allow the use of the `metric` proxy for the Riemann-specified `metric_f`.

**Comment by perezd** [comment]
OK #20 has been pushed, and npm package is now at 1.0.1 I'm going to close this and assume its fixed. Please re-open if you determine otherwise. Thanks!
