### ISSUE TITLE
Doesn't seem to work in Node 6.x?

### ISSUE THREAD

**Issue by ShermanMorrison** [perezd/riemann-nodejs-client#23]
The Getting Started example doesn't work for me in Node 6.9.4 on Windows 7x64-- it times out. I have a ruby client which is connecting to Riemann just fine, so the problem seems to be the node cient. 

Is this client no longer being maintained?

Getting Started Example

var client = require('riemann').createClient({
  host: 'some.riemann.server',
  port: 5555
});

client.on('connect', function() {
  console.log('connected!');
});

**Comment by perezd** [comment]
Hi I've been maintaining​ it, but if the protocol changed that's news to
me. Feel free to patch it if you want, I've never tested it on Windows.

**Comment by perezd** [comment]
1.1.0 I believe resolves this.
