### ISSUE TITLE
Request for new release

### ISSUE THREAD

**Issue by tonybaroneee** [perezd/riemann-nodejs-client#26]
To include https://github.com/perezd/riemann-nodejs-client/pull/25. Thanks!

**Comment by serge-medvedev** [comment]
And #27 too!

**Comment by tonybaroneee** [comment]
Any update?

**Comment by perezd** [comment]
Sorry, thought you were going to do that promise integration, was waiting
on you. Should I proceed?

**Comment by tonybaroneee** [comment]
I believe that was Serge. A release now would be preferable so we don’t have to point to the GitHub repo directly anymore in our dependency list :)

**Comment by tonybaroneee** [comment]
His promise refactor proposal in #27 can be in a separate release (if it happens at all). Thanks!

**Comment by perezd** [comment]
OK 1.1.0 is live, thanks for your contributions!

**Comment by tonybaroneee** [comment]
Thank you Derek!

**Comment by serge-medvedev** [comment]
Hello guys! Thanks for new release. I'm still thinking on that idea with promises, not ready to propose a solution.

**Comment by serge-medvedev** [comment]
So, are we ready to release 1.1.1/2.0.0?

**Comment by perezd** [comment]
Already did both
