### ISSUE TITLE
Memory leak ? 

### ISSUE THREAD

**Issue by ahungry** [perezd/riemann-nodejs-client#34]
It seems if you use only one protocol (tcp) each createClient call will cause both a tcp and udp to be opened. However, if you monitor close events, if the udp event is never actually doing anything but sitting there, and the tcp is receiving the close event, the monitorClose will never trigger the disconnect / close of the udp socket, resulting in a memory leak, as assuming you want to reinit a createClient on each failure of the tcp / close - you end up just adding more and more open udp.

I noticed this on a setup where we are pushing an event over strictly tcp, once per second, but the riemann server began losing about half the packets with early close signals.

**Comment by ahungry** [comment]
Also - in this scenario, udp is never even opened successfully, as firewall/network/load balancers are not properly forwarding udp to the riemann server - therefore, its just accumulating one extra stalled udp socket per createClient call (which is being invoked once per error condition on a failed riemann send).

I think the client should be refactored so that if the protocol to communicate is strictly tcp, it avoids any of the udp stuff (and probably vice-versa, otherwise its unnecessarily opening sockets it does not need to).

**Comment by ahungry** [comment]
Maybe this is a node / v8 issue as well

{code}
         var p = require('process')
         var net = require('net')
         var udp = require('dgram')

         var iter = 0

         while (true) {
           iter++
           if (iter % 10000 === 0) {
             var mu = p.memoryUsage()
             console.log({ rss: mu.rss / 1024 / 1024, iter })
           }

           // { rss: 34.765625, iter: 4520000 }                                                                                                                          
           //var s = net.Socket()                                                                                                                                        

           // { rss: 976.6484375, iter: 1160000 }                                                                                                                        
           var u = udp.createSocket('udp4')
         }
{code}

udp sockets are never GCed/reclaimed, even if no refs point to them, while tcp are as expected

**Comment by ahungry** [comment]
https://github.com/nodejs/node/issues/28143

**Comment by perezd** [comment]
Guessing this can be closed, thanks for the report!
