### ISSUE TITLE
Consider moving to this protobuf library.

### ISSUE THREAD

**Issue by perezd** [perezd/riemann-nodejs-client#7]
If this has lib can simplify deployment, I'm all for it.

https://github.com/fuwaneko/node-protobuf

**Comment by perezd** [comment]
We've addressed these issues as of v0.5.0

**Comment by lovell** [comment]
Hi Derek, thank you for maintaining this module.

The [commit log](https://github.com/perezd/riemann-nodejs-client/commits/master) suggests the move from the `protobuf` dependency to the pure-JS `protocol-buffers` module was not entirely successful.

You're probably aware the maintainer of the `protobuf` module [stopped maintaining](https://github.com/chrisdew/protobuf/issues/41#issuecomment-43511581) it 16+ months ago.

It looks like the `node-protobuf` module is currently well-maintained by a number of contributors, has tests and works on Node v4.

I'd be more than happy to help migrate to it if you agree this is still the right thing to do. If so, I'd be interested to know what went "wrong" in release v0.5.0 to help us add test cases to avoid it occurring again.

**Comment by perezd** [comment]
I'm all for this change, please feel free to proceed!

**Comment by lovell** [comment]
Great, thank you @perezd.

@actionshrimp would you, in principle at least, be able to help test this move given the problems you experienced in #16?

**Comment by lovell** [comment]
The code change for this itself was very easy - see https://github.com/lovell/riemann-nodejs-client/commit/40a3738e295c3de6c156c7b91b08faf8fde72610 or `npm install lovell/riemann-nodejs-client#node-protobuf`

The tests pass, plus I've configured a separate Node.js app to use this work-in-progress branch and it has happily connected with and sent events to a Riemann instance as expected.

The big gotcha here is that the `node-protobuf` module does not bundle the `libprotobuf` source code, which means that switching to it will place a new external system-wide dependency on users of this module.

The one-liner installation of protobuf and its headers for Linux/Mac can easily be documented e.g. `apt-get install libprotobuf-dev`, `yum install protobuf-devel` or `brew install protobuf`. Sadly the [Windows](https://github.com/fuwaneko/node-protobuf#windows) details are, as is so often the case, a little more complex.

The system-wide approach does bring a couple of benefits. It allows security updates to occur independently and downloading pre-built protobuf binaries will be faster than compiling from source.

Is this new dependency one we're willing to accept?

**Comment by perezd** [comment]
So this is a dependency that we cannot automate as part of the module installation? That is definitely non-ideal for new installations...perhaps we should do a major version release and hope that most people are smart enough to not just install whatever version we hand them?

**Comment by lovell** [comment]
Let's see if https://github.com/fuwaneko/node-protobuf/issues/51 can help.

**Comment by ahungry** [comment]
What about using this?  

https://www.npmjs.com/package/protobufjs

Pure javascript implementation - no OS level lib dependency for clients?

**Comment by ahungry** [comment]
@lovell @perezd pull request to change to protobufjs here:

https://github.com/perezd/riemann-nodejs-client/pull/30

**Comment by lovell** [comment]
Thanks @ahungry, I'm much less involved in the use of this module than I was 3 years ago.

Perhaps @tootedom might know of someone who would like to help review #30?

**Comment by perezd** [comment]
I've taken a pass at reviewing #30.
